logging:
  level:
    org.springframework.security: TRACE
    org.springframework.cloud.gateway: TRACE
    org.springframework.web: TRACE
    com.netflix.eureka: TRACE


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000
eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

