server:
  port: 8989

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000


spring:
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: http://localhost:8081
          predicates:
            - Path=/accounts/**
        - id: bill-service
          uri: http://localhost:8082
          predicates:
            - Path=/bills/**
        - id: deposit-service
          uri: http://localhost:8080
          predicates:
            - Path=/deposits/**
    compatibility-verifier:
      enabled: false
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
