server:
  port: 9999

spring:
  rabbitmq:
    port: 5672
    host: rabbitmq
    username: guest
    password: guest
    listener:
      direct:
        default-requeue-rejected: true
  sleuth:
    propagation:
      type: w3c,b3
    traceId128: true
    supportsJoin: false
